# Config file for preprocessing related params for amos

# General
dataset_config: amos
dataset_name: amos_spacing_1_1_2_nocrop
modality: CT
seed: 10
path_to_dataset: /apdcephfs/share_1290796/lh/AMOS22/AMOS22

# Preprocessing
train: 160
test: 20
val: 20

fixed_size: True
foreground_normalization: True
resize_shape: [256, 256, 128]
cropping: True
key: image # [image, label]
margin: 2
orientation: RAS
min_num_organs: 5